FROM node:alpine AS builder

ARG PROFILE=homologacao

WORKDIR /app

COPY . .

RUN npm install -g @angular/cli

RUN ng build --configuration=${PROFILE}

FROM nginx:alpine

COPY --from=builder /app/dist/* /usr/share/nginx/html/
